version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    shm_size: 1gb

  web_db:
    image: postgres:15
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    ports:
      - "5432:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    shm_size: 1gb


  processor:
    build: .
    volumes:
      - .:/squid
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - RPC_ENDPOINT=wss://archiver.d9network.com:40300
      - MAIN_CONTRACT_MARKET_MAKER=z8keEeLwjZFK5NS5PF6xYwTHEbm7jwpH4gBYB1JV6pDTtWg
      - MAIN_CONTRACT_CROSS_CHAIN=vNNoHwVH8af77P4s1ch14yTy7UTd8w9g2VfYA5fBExZzA7i
      - MAIN_CONTRACT_D9_USDT=uLj9DRUujbpCyK7USZY5ebGbxdtKoWvdRvGyyUsoLWDsNng
      - MAIN_CONTRACT_MERCHANT=xjyLYnZBRhYYjUKjCp8UiHnmcjHmkPfRSBxTiLLMoEwtzwp
      - MAIN_CONTRACT_BURN_MANAGER=wRGYShktZsxtKwXCCzqtLW7P1a5K2qDsaXEcRWxVYKGwH7d
      - MAIN_CONTRACT_NODE_REWARD=xqDsmMNZsCprGkjG6JPCQYysvdBs5GvudLzkXt73BbysX6D
      - LOCAL_URL=http://web1:7000
    ports:
      # prometheus metrics exposed at port 3000
      - "3000:3000"
    command: [ "node", "-r", "dotenv/config", "lib/main.js" ]
    depends_on:
      - db

  web1:
    build:
      context: ./create
    command: ["python", "manage.py", "runserver", "0.0.0.0:7000" ]
    volumes:
      - ./create:/app
    ports:
      - "7000:7000"
    depends_on:
      - web_db
    environment:
      DATABASE_URL: postgres://django_user:django_password@web_db:5432/django_db


  web2:
    build:
      context: ./list
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    volumes:
      - ./list:/app
    ports:
      - "8000:8000"
    depends_on:
      - web_db
    environment:
      DATABASE_URL: postgres://django_user:django_password@web_db:5432/django_db