version: "3"

services:

  web_db:
    image: postgres:15
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    ports:
      - "6543:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    shm_size: 1gb

  web1:
    build:
      context: ./create
    command: ["python", "manage.py", "runserver", "0.0.0.0:7000" ]
    volumes:
      - ./create:/app
    ports:
      - "7000:7000"
    depends_on:
      - web_db
    environment:
      DATABASE_URL: postgres://django_user:django_password@web_db:5432/django_db


  web2:
    build:
      context: ./list
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    volumes:
      - ./list:/app
    ports:
      - "8000:8000"
    depends_on:
      - web_db
    environment:
      DATABASE_URL: postgres://django_user:django_password@web_db:5432/django_db