# Generated by Django 5.1 on 2024-08-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreenPointTransfer',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.IntegerField()),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('merchant_points', models.CharField(max_length=255)),
                ('consumer_points', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('actions', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SwapTransfer',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.IntegerField()),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('d9', models.CharField(max_length=255)),
                ('usdt', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('actions', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.IntegerField()),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('d9', models.CharField(max_length=255)),
                ('usdt', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('actions', models.CharField(max_length=255)),
            ],
        ),
    ]
